apiVersion: v1
kind: Service
metadata:
  name: creativeforge-api-service
  namespace: creativeforge
  labels:
    app: creativeforge-api
spec:
  selector:
    app: creativeforge-api
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
