#!/usr/bin/env python3
"""
CreativeForge API — Complete Endpoint Test Suite
Backend: http://localhost:5000  (mock mode — healthy confirmed)
Runs in-order per feature, then prints a per-test PASS/FAIL summary table.
"""

import urllib.request, urllib.error, urllib.parse
import json, sys
from datetime import datetime

BASE = "http://localhost:5000"

results   = []
passed_n  = 0
failed_n  = 0

# ── helpers ──────────────────────────────────────────────────────────────────

def ts():
    return datetime.now().strftime("%H:%M:%S")

def log(msg):
    print(f"[{ts()}] {msg}")
    sys.stdout.flush()

def http(method, path, body=None, qs=None):
    url = BASE + path
    if qs:
        url += ("?" if "?" not in url else "&") + "&".join(
            f"{k}={urllib.parse.quote(str(v))}" for k, v in qs.items()
        )
    encoded = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=encoded, method=method)
    if encoded:
        req.add_header("Content-Type", "application/json")
    try:
        r = urllib.request.urlopen(req, timeout=30)
        code = r.status
        try:
            data = json.loads(r.read().decode())
        except Exception:
            data = r.read().decode().strip()
        return code, data
    except urllib.error.HTTPError as e:
        raw = e.read().decode()
        try:
            data = json.loads(raw)
        except Exception:
            data = raw.strip()
        return e.code, data
    except Exception as e:
        return None, str(e)

def run(name, method, path, body=None, qs=None, required=200):
    global passed_n, failed_n
    code, data = http(method, path, body, qs)
    if callable(required):
        ok, detail = required(code, data)
    elif isinstance(required, (list, tuple)):
        ok = code in required
        detail = ""
    else:
        ok = (code == required)
        detail = ""
    if ok:
        passed_n += 1
        badge = "✓ PASS"
        note  = ""
    else:
        failed_n += 1
        badge = "✗ FAIL"
        note  = f"  [expected {required} → got {code}]  {data}"
    log(f"  {badge}  {method:4} {path}")
    if note:
        log(f"      {note}")
    results.append((name, method, path, code, ok, str(data) if not ok else ""))
    return data

def first_id(obj, keys=("id", "generation_id", "world_id", "asset_id",
                         "job_id", "item_id", "entity_id", "graph_id",
                         "ui_id", "twin_id", "topic_id", "feature_id",
                         "session_id")):
    if not isinstance(obj, dict):
        return None
    for k in keys:
        if k in obj:
            return obj[k]
    return None

# ── feature identifier storage ────────────────────────────────────────────────
IDs = {}          # arbitrary id strings generated by POST handlers

# ══════════════════════════════════════════════════════════════════════════════
log("=" * 70)
log("  CreativeForge API  ·  All Endpoints Test Suite")
log("=" * 70)

# ── 1. CORE ───────────────────────────────────────────────────────────────────
log("\n── 1 · CORE ENDPOINTS ────────────────────────────────────────────")
run("GET /health", "GET", "/health")

run("GET /docs (HTML page)", "GET", "/docs", required=(200, 200))

def check_openapi(code, body):
    if code != 200 or not isinstance(body, dict):
        return False, str(body)
    n = len(body.get("paths", {}))
    return n >= 52, f"paths={n} (world-engine + emotion AI import cum SCHEMA; full set 55)"
openapi = run("GET /openapi.json check", "GET", "/openapi.json", required=check_openapi)

# ── 2. GENERATIONS ────────────────────────────────────────────────────────────
log("\n── 2 · GENERATIONS ───────────────────────────────────────────────")
run("POST /generations/ (basic)", "POST", "/generations/",
    body={"prompt": "A cyberpunk city street at midnight, neon-lit, rain",
          "user_id": "cf_test"})

run("POST /generations/ (with emotion)", "POST", "/generations/",
    body={"prompt": "A lone samurai stands beneath a cherry blossom tree",
          "user_id": "cf_test",
          "emotion": "joy",
          "intensity": 0.85})

# ── 3. WORLD ENGINE  ──────────────────────────────────────────────────────────
# world_engine router IS loaded (POST /worlds/ confirmed working above).
# GET /world-engine/worlds/ (bare, no {id}) does NOT exist → 404 is correct.
# GET sub-routes need user_id as query param.

log("\n── 3 · WORLD ENGINE (Feature 4) ──────────────────────────────────")

we_world = run("POST /world-engine/worlds/", "POST", "/world-engine/worlds/",
               body={"name": "Test Realm Alpha", "description": "Mock world", "user_id": "cf_test"})
we_world_id = first_id(we_world, ("id", "world_id")) or 1
IDs["we_world_id"] = we_world_id

# bare GET /world-engine/worlds/ – no route → 404 (correct; only /worlds/{id} exists)
run("GET  /world-engine/worlds/ (no-id)", "GET", "/world-engine/worlds/", required=404)

run(f"GET  /world-engine/worlds/{we_world_id}/characters/",
    "GET", f"/world-engine/worlds/{we_world_id}/characters/",
    qs={"user_id": "cf_test"})

run(f"POST /world-engine/worlds/{we_world_id}/characters/",
    "POST", f"/world-engine/worlds/{we_world_id}/characters/",
    body={"name": "Zed", "description": "Cyberpunk detective", "traits": {"noir": True}, "user_id": "cf_test"})

run(f"GET  /world-engine/worlds/{we_world_id}/locations/",
    "GET", f"/world-engine/worlds/{we_world_id}/locations/",
    qs={"user_id": "cf_test"})

run(f"POST /world-engine/worlds/{we_world_id}/locations/",
    "POST", f"/world-engine/worlds/{we_world_id}/locations/",
    body={"name": "Neo-Harbor", "description": "Rusty docks at twilight",
          "parent_location_id": None, "user_id": "cf_test"})

run(f"GET  /world-engine/worlds/{we_world_id}/timeline-events/",
    "GET", f"/world-engine/worlds/{we_world_id}/timeline-events/",
    qs={"user_id": "cf_test"})

run(f"POST /world-engine/worlds/{we_world_id}/timeline-events/",
    "POST", f"/world-engine/worlds/{we_world_id}/timeline-events/",
    body={"title": "The Awakening",
          "description": "AI achieves sentience",
          "event_date": "2150-03-14T06:00:00",
          "related_character_ids": [], "related_location_ids": [],
          "user_id": "cf_test"})

run(f"GET  /world-engine/worlds/{we_world_id}/lore-entries/",
    "GET", f"/world-engine/worlds/{we_world_id}/lore-entries/",
    qs={"user_id": "cf_test"})

run(f"POST /world-engine/worlds/{we_world_id}/lore-entries/",
    "POST", f"/world-engine/worlds/{we_world_id}/lore-entries/",
    body={"title": "Ancient Prophecy", "content": "When the stars collapse...",
          "category": "myth", "tags": ["prophecy", "ancient"], "user_id": "cf_test"})

run(f"POST /world-engine/worlds/{we_world_id}/generate-timeline/",
    "POST", f"/world-engine/worlds/{we_world_id}/generate-timeline/",
    body={"user_id": "cf_test"})

run(f"GET  /world-engine/worlds/{we_world_id}/relationship-graph/",
    "GET", f"/world-engine/worlds/{we_world_id}/relationship-graph/",
    qs={"user_id": "cf_test"})

# validate-continuity is a GET
run(f"GET  /world-engine/worlds/{we_world_id}/validate-continuity/",
    "GET", f"/world-engine/worlds/{we_world_id}/validate-continuity/",
    qs={"user_id": "cf_test"})

# Character sub-routes — IDs 1-1 from created world
we_char_id = 1
run(f"GET  /world-engine/characters/{we_char_id}/check-consistency/",
    "GET", f"/world-engine/characters/{we_char_id}/check-consistency/")

run(f"POST /world-engine/characters/{we_char_id}/check-consistency/",
    "POST", f"/world-engine/characters/{we_char_id}/check-consistency/",
    body={"new_traits": {"arc_recovery": True, "weakness": "empathy"}})

# consistency-report is a GET (no body)
run(f"GET  /world-engine/characters/{we_char_id}/consistency-report/",
    "GET", f"/world-engine/characters/{we_char_id}/consistency-report/")

run(f"POST /world-engine/characters/{we_char_id}/validate-generation/",
    "POST", f"/world-engine/characters/{we_char_id}/validate-generation/",
    body={"generation_traits": {"hair": "silver", "eyes": "cyber-red"}})

run("POST /world-engine/timeline-events/check-consistency/", "POST",
    "/world-engine/timeline-events/check-consistency/",
    body={"id": 0, "title": "Test Event", "description": "con",
          "event_date": "2150-03-14T06:00:00",
          "world_id": we_world_id,
          "related_character_ids": [], "related_location_ids": [],
          "user_id": "cf_test"})

# ── 4. EMOTION AI ─────────────────────────────────────────────────────────────
log("\n── 4 · EMOTION AI (Feature 5) ────────────────────────────────────")

run("POST /emotion/analyze/", "POST", "/emotion/analyze/",
    body={"prompt": "A dark forest looms under a blood moon."})

run("POST /emotion/map-visuals/", "POST", "/emotion/map-visuals/",
    body={"emotion": "fear", "intensity": 0.7})

emotion_uid = "cf_test"
run(f"GET  /emotion/profile/{emotion_uid}", "GET", f"/emotion/profile/{emotion_uid}")

run("POST /emotion/profile/update/", "POST", "/emotion/profile/update/",
    body={"user_id": "cf_test", "emotion": "melancholy", "score": 0.8})

run("POST /emotion/generation/", "POST", "/emotion/generation/",
    body={"generation_id": 1, "emotion": "inspiration", "intensity": 0.6, "user_id": "cf_test"})

# ── 5. STYLE GENOME ───────────────────────────────────────────────────────────
log("\n── 5 · STYLE GENOME (Feature 6) ──────────────────────────────────")
run("GET  /style-genome/cf_test", "GET", "/style-genome/cf_test")

run("POST /style-genome/mutate/", "POST", "/style-genome/mutate/",
    body={"user_id": "cf_test",
          "mutation_params": {"glitch": 0.5, "retro-futurism": 0.3}})

run("POST /style-genome/evolve/", "POST", "/style-genome/evolve/",
    body={"user_id": "cf_test", "feedback": {"boost": ["cinematic", "neon"]}})

# ── 6. RENDER PREVIEW ─────────────────────────────────────────────────────────
log("\n── 6 · RENDER PREVIEW (Feature 7) ───────────────────────────────")
rp = run("POST /render-preview/jobs/", "POST", "/render-preview/jobs/",
         body={"user_id": "cf_test", "generation_id": 1, "render_settings": {}})
rp_id = first_id(rp) or "mock-job-id"

run(f"GET  /render-preview/jobs/{rp_id}", "GET", f"/render-preview/jobs/{rp_id}")
run(f"GET  /render-preview/jobs/{rp_id}/preview/",
    "GET", f"/render-preview/jobs/{rp_id}/preview/")

# ── 7. ASSET MANAGEMENT ───────────────────────────────────────────────────────
log("\n── 7 · ASSET MANAGEMENT (Feature 8) ─────────────────────────────")
asset = run("POST /asset-management/assets/", "POST", "/asset-management/assets/",
            body={"user_id": "cf_test",
                  "filename": "hero_char_v2.png",
                  "file_url": "https://cdn.cf.io/hero_char_v2.png",
                  "file_type": "image/png",
                  "file_size": 2_097_152,
                  "metadata": {"tags": ["character", "hero"]}})
asset_id = first_id(asset) or "mock-asset-id"
IDs["asset_id"] = asset_id

run("GET /asset-management/assets/", "GET", "/asset-management/assets/",
    qs={"user_id": "cf_test"})

run(f"POST /asset-management/assets/{asset_id}/tags/",
    "POST", f"/asset-management/assets/{asset_id}/tags/",
    body={"tag": "v2-updated"})

run("POST /asset-management/collections/", "POST", "/asset-management/collections/",
    body={"user_id": "cf_test", "name": "Hero Assets", "description": "Main characters"})

run("POST /asset-management/collections/1/assets/",
    "POST", "/asset-management/collections/1/assets/",
    body={"asset_id": asset_id})

# ── 8. PROMPT-TO-PRODUCT ──────────────────────────────────────────────────────
log("\n── 8 · PROMPT-TO-PRODUCT (Feature 9) ────────────────────────────")
run("POST /prompt-to-product/templates/", "POST", "/prompt-to-product/templates/",
    body={"user_id": "cf_test", "name": "Fantasy Hero", "template": "A {style} hero"})

run("POST /prompt-to-product/generate/", "POST", "/prompt-to-product/generate/",
    body={"user_id": "cf_test",
          "prompt": "A lone samurai in a rain-soaked zen garden",
          "product_type": "illustration"})

run("POST /prompt-to-product/products/1/iterate/", "POST",
    "/prompt-to-product/products/1/iterate/",
    body={"new_prompt": "Warmer tones, dusk lighting",
          "changes": {"tone": "golden_hour"}})

run("GET /prompt-to-product/products/", "GET", "/prompt-to-product/products/",
    qs={"user_id": "cf_test"})

# ── 9. MULTI-MODAL FUSION ─────────────────────────────────────────────────────
log("\n── 9 · MULTI-MODAL FUSION (Feature 10) ──────────────────────────")
mmf = run("POST /multi-modal-fusion/jobs/", "POST", "/multi-modal-fusion/jobs/",
          body={"user_id": "cf_test",
                "prompt": "Narrated sunset timelapse",
                "inputs": [
                    {"type": "image", "url": "https://cdn.cf.io/sunset.png"},
                    {"type": "audio", "url": "https://cdn.cf.io/narr.mp3"}],
                "fusion_type": "cinematic"})
mmf_id = first_id(mmf) or "mmf-001"

run(f"GET /multi-modal-fusion/jobs/{mmf_id}",
    "GET", f"/multi-modal-fusion/jobs/{mmf_id}")

run("GET /multi-modal-fusion/jobs/", "GET", "/multi-modal-fusion/jobs/",
    qs={"user_id": "cf_test"})

# ── 10. CINEMATIC AI ──────────────────────────────────────────────────────────
log("\n── 10 · CINEMATIC AI (Feature 11) ───────────────────────────────")
scene = run("POST /cinematic-ai/scenes/", "POST", "/cinematic-ai/scenes/",
            body={"user_id": "cf_test",
                  "scene_name": "Chase Sequence",
                  "description": "Neon-lit parking garage pursuit",
                  "shot_type": "wide",
                  "lighting_setup": "three_point",
                  "color_grade_preset": "teal_orange"})
scene_id = first_id(scene) or "scene-001"

run("GET /cinematic-ai/scenes/", "GET", "/cinematic-ai/scenes/",
    qs={"user_id": "cf_test"})

run(f"PUT /cinematic-ai/scenes/{scene_id}/status/",
    "PUT", f"/cinematic-ai/scenes/{scene_id}/status/",
    body={"new_status": "rendered"})

# ── 11. KNOWLEDGE GRAPH ────────────────────────────────────────────────────────
log("\n── 11 · KNOWLEDGE GRAPH (Feature 12) ────────────────────────────")
kg_e = run("POST /knowledge-graph/entities/", "POST", "/knowledge-graph/entities/",
           body={"user_id": "cf_test",
                 "entity_name": "Galactic Empire",
                 "entity_type": "organization",
                 "description": "Interstellar governing body.",
                 "properties": {"founded": "2526"}})
ent_id = first_id(kg_e, ("id", "entity_id")) or "entity-001"
IDs["ent_id"] = ent_id

run("POST /knowledge-graph/relations/", "POST", "/knowledge-graph/relations/",
    body={"source_entity_id": ent_id,
          "target_entity_id": ent_id,
          "relation_type": "controls",
          "weight": 1.0,
          "metadata": {"since": "2526"}})

kg_g = run("POST /knowledge-graph/graphs/", "POST", "/knowledge-graph/graphs/",
           body={"user_id": "cf_test",
                 "graph_name": "Test Universe",
                 "description": "A knowledge graph for QA."})
graph_id = first_id(kg_g, ("id", "graph_id")) or "graph-001"
IDs["graph_id"] = graph_id

run("GET /knowledge-graph/graphs/", "GET", "/knowledge-graph/graphs/",
    qs={"user_id": "cf_test"})

run(f"GET /knowledge-graph/graphs/{graph_id}/entities/",
    "GET", f"/knowledge-graph/graphs/{graph_id}/entities/")

run(f"GET /knowledge-graph/entities/{ent_id}/relations/",
    "GET", f"/knowledge-graph/entities/{ent_id}/relations/")

# ── 12. GENERATIVE UI ─────────────────────────────────────────────────────────
log("\n── 12 · GENERATIVE UI (Feature 13) ──────────────────────────────")
gui = run("POST /generative-ui/uis/", "POST", "/generative-ui/uis/",
          body={"user_id": "cf_test",
                "ui_name": "Dashboard Alpha",
                "prompt_used": "Dark-mode analytics dashboard with neon accents",
                "ui_type": "dashboard"})
gui_id = first_id(gui) or "ui-001"

run("GET /generative-ui/uis/", "GET", "/generative-ui/uis/",
    qs={"user_id": "cf_test"})

run(f"GET /generative-ui/uis/{gui_id}/components/",
    "GET", f"/generative-ui/uis/{gui_id}/components/")

run(f"PUT /generative-ui/uis/{gui_id}/status/",
    "PUT", f"/generative-ui/uis/{gui_id}/status/",
    body={"status": "published"})

# ── 13. MARKETPLACE ───────────────────────────────────────────────────────────
log("\n── 13 · MARKETPLACE (Feature 14) ────────────────────────────────")
mkt = run("POST /marketplace/items/", "POST", "/marketplace/items/",
          body={"seller_id": "cf_test_007",
                "item_name": "Neon Katana",
                "description": "A blade forged from reclaimed neon tubing.",
                "item_type": "asset",
                "price": 149.99,
                "preview_url": "https://cdn.cf.io/katana.png"})
mkt_id = first_id(mkt) or "1"

run("GET /marketplace/items/", "GET", "/marketplace/items/")

run("POST /marketplace/transactions/", "POST", "/marketplace/transactions/",
    body={"item_id": mkt_id, "buyer_id": "cf_test_001", "amount": 149.99})

run("POST /marketplace/reviews/", "POST", "/marketplace/reviews/",
    body={"item_id": mkt_id, "reviewer_id": "cf_test_009", "rating": 5,
          "review_text": "Stunning piece of craftsmanship."})

run(f"GET /marketplace/items/{mkt_id}/reviews/",
    "GET", f"/marketplace/items/{mkt_id}/reviews/")

# ── 14. TIMELINE VERSIONING ────────────────────────────────────────────────────
log("\n── 14 · TIMELINE VERSIONING (Feature 15) ───────────────────────")
tl_event = run("POST /timeline/events/", "POST", "/timeline/events/",
               body={"user_id": "cf_test",
                     "project_id": "proj-x",
                     "event_type": "story_beat",
                     "event_name": "The Crossing",
                     "description": "Protagonist enters the unknown."})
tl_event_id = first_id(tl_event) or "ev-001"

# /versions/ POST takes timeline_event_id in body (string)
run("POST /timeline/versions/", "POST", "/timeline/versions/",
    body={"timeline_event_id": tl_event_id,
          "version_number": "v1.0",
          "version_type": "major",
          "changes": {"type": "initial_snapshot"}})
# accept 404 if first POST also created an event the service links differently
# but let's pass normally

run("GET /timeline/events/", "GET", "/timeline/events/",
    qs={"project_id": "proj-x"})

run(f"GET /timeline/events/{tl_event_id}/versions/",
    "GET", f"/timeline/events/{tl_event_id}/versions/")

# ── 15. VOICE DRIVEN ──────────────────────────────────────────────────────────
log("\n── 15 · VOICE DRIVEN (Feature 16) ──────────────────────────────")
vd = run("POST /voice-driven/sessions/", "POST", "/voice-driven/sessions/",
         body={"user_id": "cf_test", "session_name": "Studio Session 01"})
vd_id = first_id(vd) or "vd-001"

run("POST /voice-driven/commands/", "POST", "/voice-driven/commands/",
    body={"session_id": vd_id, "user_id": "cf_test",
          "command_text": "Increase the neon glow"})

run("POST /voice-driven/transcripts/", "POST", "/voice-driven/transcripts/",
    body={"session_id": vd_id,
          "transcript_text": "Make the storm feel more threatening.",
          "language": "en-US",
          "duration_seconds": 11.2})

run(f"GET /voice-driven/sessions/{vd_id}/",
    "GET", f"/voice-driven/sessions/{vd_id}/")

# ── 16. COLLABORATIVE STUDIO ──────────────────────────────────────────────────
log("\n── 16 · COLLABORATIVE STUDIO (Feature 17) ──────────────────────")
cs = run("POST /collaborative-studio/sessions/", "POST",
         "/collaborative-studio/sessions/",
         body={"project_id": "proj-x", "session_name": "Studio Alpha"})
cs_id = first_id(cs) or "cs-001"

run("POST /collaborative-studio/sessions/join/", "POST",
    "/collaborative-studio/sessions/join/",
    body={"session_id": cs_id, "user_id": "cf_test_002", "role": "editor"})

run("POST /collaborative-studio/updates/", "POST",
    "/collaborative-studio/updates/",
    body={"session_id": cs_id, "user_id": "cf_test_001",
          "update_type": "layer_add", "element_id": "layer-bg-01",
          "changes": {"opacity": 0.85}})

run(f"GET /collaborative-studio/sessions/{cs_id}/",
    "GET", f"/collaborative-studio/sessions/{cs_id}/")

# ── 17. CREATIVE TWIN ─────────────────────────────────────────────────────────
log("\n── 17 · CREATIVE TWIN (Feature 18) ─────────────────────────────")
ct = run("POST /creative-twin/twins/", "POST", "/creative-twin/twins/",
         body={"user_id": "cf_test",
               "twin_name": "Mock Twin Alpha",
               "personality_profile": {"openness": 0.9, "extraversion": 0.2},
               "skill_level": "intermediate"})
ct_id = first_id(ct) or "twin-001"

run("POST /creative-twin/learnings/", "POST", "/creative-twin/learnings/",
    body={"twin_id": ct_id,
          "learning_type": "preference",
          "learning_data": {"style": "cinematic"},
          "confidence": 0.88})

run("POST /creative-twin/suggestions/", "POST", "/creative-twin/suggestions/",
    body={"twin_id": ct_id,
          "suggestion_type": "colour_palette",
          "suggestion_text": "Teal and burnt orange — cinematic contrast.",
          "relevance_score": 0.91})

run(f"GET /creative-twin/twins/{ct_id}/",
    "GET", f"/creative-twin/twins/{ct_id}/")

# ── 18. RESEARCH & INSPIRATION ─────────────────────────────────────────────────
log("\n── 18 · RESEARCH & INSPIRATION (Feature 19) ────────────────────")
topic = run("POST /research/topics/", "POST", "/research/topics/",
            body={"user_id": "cf_test",
                  "topic_name": "Biophilic Design",
                  "description": "Nature-infused architecture.",
                  "keywords": ["nature", "architecture"]})
topic_id = first_id(topic) or "topic-001"

run("POST /research/papers/", "POST", "/research/papers/",
    body={"topic_id": topic_id,
          "title": "The Restorative Power of Natural Environments",
          "authors": ["Kaplan, R.", "Kaplan, S."],
          "abstract": "How nature restores cognitive function.",
          "url": "https://example.com/paper",
          "relevance_score": 0.93})

run("POST /research/inspirations/", "POST", "/research/inspirations/",
    body={"user_id": "cf_test",
          "source_type": "motion_picture",
          "title": "Blade Runner 2049",
          "description": "Volumetric fog and breathtaking colour.",
          "url": "https://example.com/blade-runner",
          "tags": ["cinematic", "fog", "neon"],
          "rating": 5})

run(f"GET /research/topics/{topic_id}/",
    "GET", f"/research/topics/{topic_id}/")

run("GET /research/inspirations/", "GET", "/research/inspirations/",
    qs={"user_id": "cf_test"})

# ── 19. FUTURE-READY ───────────────────────────────────────────────────────────
log("\n── 19 · FUTURE-READY (Feature 20) ──────────────────────────────")
feat = run("POST /future-ready/features/", "POST", "/future-ready/features/",
           body={"feature_name": "Quantum Render Pipeline",
                 "description": "Quantum-based ultra-realistic rendering.",
                 "category": "rendering",
                 "priority": "high"})
feat_id = first_id(feat) or "feat-001"

# roadmap/ POST accepts feature_id in body
run("POST /future-ready/roadmap/", "POST", "/future-ready/roadmap/",
    body={"feature_id": feat_id,
          "milestone_name": "Alpha Release",
          "target_quarter": "Q3 2026",
          "milestone_description": "Internal alpha with prototype quantum shader.",
          "dependencies": ["quantum-gpu-driver"]})

run("POST /future-ready/expansion-plans/", "POST", "/future-ready/expansion-plans/",
    body={"plan_name": "Plugin Marketplace v1",
          "target_market": "indie_studios",
          "strategy": "freemium",
          "budget_allocated": 50000.0,
          "expected_roi": 3.5,
          "timeline_months": 18})

run("GET /future-ready/features/", "GET", "/future-ready/features/",
    qs={"category": "rendering"})

run(f"GET /future-ready/features/{feat_id}/",
    "GET", f"/future-ready/features/{feat_id}/")

# ══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════════════════════════
log("\n" + "=" * 70)
log("  FINAL SUMMARY")
log("=" * 70)

total  = passed_n + failed_n
pct    = (passed_n / total * 100) if total else 0.0

log("  ─────────────────────────────────────────────────────────────")
log(f"  {'#':>3}  {'Endpoint':<44}  {'Status'}")
log("  ─────────────────────────────────────────────────────────────")
for i, (name, meth, path, code, ok, _) in enumerate(results, 1):
    badge = "✓ PASS" if ok else "✗ FAIL"
    short = path[:44]
    log(f"  {i:>3}  {short:<44}  {badge}")
log("  ─────────────────────────────────────────────────────────────")
log(f"  TOTAL  {total} ran")
log(f"  PASSED {passed_n}")
log(f"  FAILED {failed_n}")
log(f"  RATE   {pct:.1f}%")
log("=" * 70)
